name: Workflow Test
on: push

jobs:
  first:
    name: Step One
    runs-on: ubuntu-latest
    container: alpine/git
    steps:
      - run: echo "$GITHUB_SERVER_URL"
      - run: |
          HOST=$(echo "$GITHUB_SERVER_URL" | sed 's%https://%%')
          URL="https://$GITHUB_TOKEN@$HOST/$GITHUB_REPOSITORY.git"
          git clone "$URL" .
      - run: ls
